services:
  app:
    build: .
    container_name: simple-chat-app
    restart: unless-stopped
    depends_on:
      - mysql
    environment:
      PORT: 3000
      DB_HOST: mysql
      DB_PORT: 3306
      DB_USER: kamila
      DB_PASSWORD: KY2fAeolV91mI0iZ
      DB_NAME: simple_chat
      JWT_SECRET: change-this-to-a-long-random-secret
      JWT_EXPIRES_IN: 7d
    ports:
      - "3000:3000"
    volumes:
      - uploads:/app/public/uploads

  mysql:
    image: mysql:8.4
    container_name: simple-chat-mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: KY2fAeolV91mI0iZ
      MYSQL_DATABASE: simple_chat
      MYSQL_USER: kamila
      MYSQL_PASSWORD: KY2fAeolV91mI0iZ
    volumes:
      - mysql-data:/var/lib/mysql
      - ./database/schema.sql:/docker-entrypoint-initdb.d/01-schema.sql:ro

volumes:
  mysql-data:
  uploads:
